---
date: 2026-09-17
verdict: HOLD
strategy: pbr_value_v1
conditions: [size tercile(절대 임계값), sector(config/sectorGroups.json 20그룹), realized-vol tercile(전체분포), trigger 10~50%, fraction 50%, 잔여분 트레일링 2~25%]
reason: >-
  partial-exit-scale-out-2026-09.md(HOLD)의 세그먼트 분해. 시가총액은 뚜렷하게
  갈린다 - 대형(N=122)은 전 트리거가 기준선(전량보유) Sharpe 0.4285보다
  낮아 개선 없음, 중형(N=344)·소형(N=275)은 +40%에서 Sharpe 0.45->0.55로
  일관되게 개선. 변동성 3분위(N=251/252/251, 전체분포 컷오프)는 저/중/고
  전부 최적 트리거가 +40%로 일치해 "저변동은 낮은 %에" 가설을 기각하되,
  세 독립 세그먼트가 같은 값에 모인 것 자체가 +40%의 견고성을 오히려
  뒷받침한다. 업종(20그룹)은 최적 트리거가 10~50%로 산개하고 N이 0~119로
  들쭉날쭉해(반도체·정유·항공방산·미디어 N=0) 판정 근거로 못 쓴다. 중형주는
  +40% 매도 뒤 잔여분을 3% 트레일링으로 추가하면 Sharpe 0.55->0.64로 더
  개선되고, 이건 격자 경계값이 아니라 2~7% 재스윕에서 확인한 진짜 봉우리다
  (51건 부분매도 중 50건이 발동). 소형주 최적(20%, 0.68)은 15%에서 움푹
  파지는 비단조 패턴이라 노이즈 가능성이 있어 판정에서 뺀다.
cagr: null
sharpe: 0.6445
mdd: -8.36
---

# 부분 익절 트리거 — 시가총액·변동성·업종별로 최적 %가 다른가

## 배경

`partial-exit-scale-out-2026-09.md`(2026-09-04, HOLD)가 "+10~30%에서 부분
익절이 12/12 격자점에서 개선된다"까지는 확인했지만 전 종목에 같은 %를
적용했다. 사용자 질문: "모든 기업에 똑같이 40%를 적용하는 건 단편적이지
않나 — 회사 크기·업종·변동성에 따라 다르게 정할 수 있나?"

같은 엔진(`partial_exit_sweep.py`, 체결·비용 규약 무변경)을 재사용하고,
새로 만든 `partial_exit_segment_sweep.py`가 거래를 세그먼트로 나눠 같은
격자(트리거 10~50%, 매도비율 50% 고정)를 세그먼트별로 돌린다.

## [1] 시가총액 — 뚜렷하게 갈린다, 신뢰 가능

절대 임계값([ASSUMPTION], KOSPI 200/미드200 관행): 대형 >=1조원 · 중형
2천억~1조원 · 소형 <2천억원. 진입일 시가총액 = entry_fill.fill_price ×
A3c 발행주식수(PIT).

| 크기군 | N | 기준 Sharpe | 최적 트리거 | 최적 Sharpe |
|---|---:|---:|---:|---:|
| 대형 | 122 | 0.4285 | 없음(전 트리거가 기준보다 낮음) | - |
| 중형 | 344 | 0.4531 | +40% | 0.5518 |
| 소형 | 275 | 0.4519 | +40% | 0.5531 |

**대형주는 부분 익절이 안 통한다** — 테스트한 5개 트리거(10~50%) 전부
전량보유보다 Sharpe가 낮다. 대형주는 변동성이 낮고 추세가 꾸준해 일부를
미리 팔면 상승분만 깎인다는 해석과 일치한다. **중소형주는 +40%에서 절반
매도가 일관되게 낫다** — 지난 finding의 30%보다 이번 실측은 40%를 가리킨다.

## [2] 변동성 3분위 — "낮으면 낮은 %에" 가설 기각, 그러나 +40%가 더 견고해짐

진입 직전 60거래일 일간수익률 표준편차(연율화). 전체 거래(N=768) 분포의
3분위로 저/중/고를 가른다 — 이건 **연구용 관측**이다. 실시간 판정에 쓰려면
롤링/확장 윈도우 백분위로 바꿔야 PIT-safe하다(지금은 전체 표본으로 컷오프를
낸다).

| 변동성군 | N | 기준 Sharpe | 최적 트리거 | 최적 Sharpe |
|---|---:|---:|---:|---:|
| 저변동 | 251 | 0.2829 | +40% | 0.3607 |
| 중변동 | 252 | 0.2828 | +40% | 0.3396 |
| 고변동 | 251 | 0.5618 | +40% | 0.7151 |

**"변동성 낮은 종목은 낮은 %에서 팔아야 한다"는 근거가 없다** — 세 그룹
전부 +40%로 일치한다. 다만 세 개의 독립된 250건대 표본이 우연히 같은
값에 모일 확률은 낮으므로, 오히려 **+40%가 특정 세그먼트의 우연이 아니라
이 전략 전반에 걸친 값**이라는 근거로 읽는다. 고변동군은 기준선 자체가
가장 좋고(Sharpe 0.56) 개선폭도 가장 크다(0.56→0.72) — "어떤 종목이 부분
익절의 덕을 가장 많이 보는가"에 대한 답이지 "%를 다르게 정해야 하는가"에
대한 답은 아니다.

## [3] 업종(20그룹) — 판정에 못 쓴다, 관측만

config/sectorGroups.json(KSIC→20그룹)으로 나누면 최적 트리거가 10%~50%로
전 구간에 흩어진다. 업종 20개 × 트리거 5개 = 100칸을 훑으면서 난수
바닥선 없이 "이 업종은 X%가 최고"를 고르면 2026-09-02에 데였던 다중검정
함정과 같은 모양이 된다. 게다가 **반도체·정유·항공방산·미디어·엔터는
거래 0건**이다 — pbr_value_v1(저PBR 가치주)은 성장/사이클 업종을 애초에
잘 안 사서, "반도체는 사이클이 기니까 오래 들고 가야 한다" 같은 가설
자체를 이 전략 데이터로는 검증할 수 없다. 유일하게 신뢰할 만한 관측은
유통·소비재(N=102)의 기준선 Sharpe가 이미 음수(-0.08)라는 것 — 부분익절
문제가 아니라 이 업종엔 이 전략 자체가 안 맞는다.

## [4] 잔여분 트레일링 손절 — 중형주는 진짜 봉우리를 찾았다

"+15% 트레일링"은 지난 대화에서 설명용으로 즉석에서 든 숫자였지 검증된 값이
아니었다. `--trail-sweep`(신규 모드, `measure()`의 기존 `trail_pct` 인자를
그대로 씀 - 엔진 무변경)로 고정 트리거 40%·매도 50% 뒤 잔여분 트레일링 %를
격자로 스윕했다.

| 세그먼트 | 트리거만 | 트레일링 5% | 10% | 15% | 20% | 25% |
|---|---:|---:|---:|---:|---:|---:|
| 중형(N=344) | 0.5518 | 0.6379 | 0.6205 | 0.5886 | 0.5883 | 0.5863 |
| 소형(N=275) | 0.5531 | 0.6616 | 0.6526 | 0.6074 | **0.6772** | 0.6763 |

중형이 5%→25%로 갈수록 단조 감소해 "5%가 최적"이 아니라 격자 경계에 걸린
것으로 보고, 2~7%를 다시 촘촘히 스윕:

| 트레일링 | 2% | 3% | 4% | 5% | 6% | 7% |
|---|---:|---:|---:|---:|---:|---:|
| Sharpe | 0.6417 | **0.6445** | 0.6409 | 0.6379 | 0.6324 | 0.6327 |

**3%에서 봉우리, 2%·4%도 인근(0.64대) — 경계값이 아니라 진짜 극대점이다.**
51건의 부분매도 중 50건이 이 타이트한 트레일링에 실제로 걸렸다(MDD도
-10.10%→-8.36%로 추가 개선). **최종 후보 규칙(중형주): +40%에서 50% 매도,
잔여분은 고점 대비 3% 밀리면 전량 청산.**

소형주의 20%(0.6772)는 15%(0.6074)에서 움푹 파지는 비단조 패턴이라 트레일링
발동 건수(48→27건으로 감소)가 적어지면서 생긴 노이즈일 가능성이 있다 -
**판정에 안 쓴다.** 재확인하려면 소형주도 촘촘한 재스윕이 필요하다(다음 후보).

## [5] 소형주 트레일링 재스윕(1%p 단위, 10~30%) — 노이즈 확정

5점 격자의 그리드 경계 의심을 확인하려고 `--trail-grid`를 10~30%까지 1%p
단위(21점)로 재실행(N=276, 5점 격자 때보다 1건 많음 — 오늘 git pull로
받은 최신 데이터 반영분, 무시 가능한 차이).

| 트레일링 | 10% | 12% | 14% | **15%** | 17% | **18%** | **20%** | 22% | **24%** | 25% | 27% | 30% |
|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| Sharpe | 0.6423 | 0.6250 | 0.6069 | 0.5935 | 0.5919 | 0.6430 | 0.6667 | 0.6611 | **0.6716** | 0.6713 | 0.6625 | 0.6360 |

중형주 3%처럼 좌우로 단조 감소하는 단일 극대점이 **아니다.** 10%대에서
한 번(0.64대), 18~27%대에서 또 한 번(0.65~0.67) 솟는 이봉(bimodal) 곡선이고
그 사이 15~17%는 트로프다. 5점 격자 때 "봉우리"로 보였던 20%(0.6772)가
1%p 단위 재현에서는 0.6667로 내려앉았고 실제 최댓값은 24%(0.6716)로
자리를 옮겼다 — **격자를 촘촘히 할수록 최적값이 이동한다는 것 자체가
안정된 극값이 아니라는 증거다.** 트레일링 발동 건수도 10%에서 45건이던
것이 24%에서 28건, 30%에서 21건으로 줄어(전체 부분매도 48건 중), 넓은
트레일링일수록 "트레일링 없음" 기준선(0.5497)에 가까워지되 표본이
얇아지며 흔들리는 모양과 일치한다.

**결론: 소형주 트레일링은 재론하지 않는다.** 40%에서 50% 매도까지만
채택 후보에 남기고, 잔여분 트레일링은 미채택(노이즈로 확정 — 재스윕
필요 항목 종결, 아래 판정·한계 갱신).

## [6] TRAIN/VALID/TEST 구간별 분해 — 중형주 후보가 VALID를 깎는다

`measure()`가 이미 매 실행마다 프로젝트 표준 구간(TRAIN<=2022-05-31 <
VALID<=2023-12-28 < TEST, 시간순 60/15/25)으로 나눈 Sharpe를 `segments`
필드에 저장하고 있었다 - 재실행이 아니라 저장된 JSON을 읽기만 하면 되는
줄 알았으나, [1]·[4]의 `pbr_value_v1_size.json`은 어제(09-17, git pull
이전) 데이터라 오늘 [5]에서 쓴 데이터(git pull 이후, N이 미세하게 다름)와
섞으면 비교가 안 맞는다. 그래서 baseline·+40%·+40%+트레일링을 **한 번의
실행 안에서** 같이 뽑아 비교 가능하게 만들었다(`--trail-sweep --trail-
segments 중형,소형 --trail-grid 3,20`, N=335/276 - [1]의 344/275, [5]의
276과 또 다르다. **A5/A1a는 매일 갱신되므로 이 표의 N은 "오늘 시점"
스냅샷이지 고정값이 아니다** - 원 finding의 344/275도 그때는 맞았다).

| 세그먼트 | 규칙 | ALL | TRAIN | VALID | TEST |
|---|---|---:|---:|---:|---:|
| 중형(N=335) | 전량 보유(기준) | 0.4865 | 0.4350 | **0.2033** | 0.7541 |
| 중형 | +40% 매도만 | 0.5922 | 0.5285 | 0.1610 | 0.9823 |
| 중형 | +40%매도+3%트레일링(후보) | 0.6873 | 0.6329 | **0.0906** | 1.1890 |
| 소형(N=276) | 전량 보유(기준) | 0.4491 | 0.6655 | 0.1628 | 0.0867 |
| 소형 | +40% 매도만(후보) | 0.5497 | 0.7566 | **0.2151** | 0.2123 |
| 소형 | (참고, 미채택) +40%+3%트레일 | 0.6543 | 0.7629 | 0.3464 | 0.5237 |

**중형주 후보 규칙은 원 finding(`partial-exit-scale-out-2026-09.md`)이
경고했던 것과 같은 모양으로 VALID를 깎는다.** 규칙을 더할수록(기준→
트리거만→트리거+트레일링) TRAIN·TEST는 단조 개선(0.435→0.633,
0.754→1.189)하는데 **VALID는 단조 악화**한다(0.2033→0.1610→0.0906) -
부호반전은 없지만(전부 양수), 이 프로젝트 표준 판정 기준("TRAIN 최선이
VALID·TEST에서도 상위 유지", `report_tier2_oos.py`)을 엄격히 적용하면
TRAIN 최선(트레일링 3%)이 VALID에서는 세 변형 중 꼴찌라 **통과 못한다.**
ALL 헤드라인 개선(0.45→0.69)의 상당 부분이 VALID를 깎아 TEST를 부풀린
결과일 가능성이 있다.

**소형주 후보(+40%매도만)는 반대로 TRAIN·VALID·TEST 전부 개선한다**
(0.666→0.757 / 0.163→0.215 / 0.087→0.212) - 부호반전 없고 순위 역전도
없어 표준 기준을 그대로 통과한다. (표에 넣은 소형주 트레일링 3%는
[5]에서 이미 노이즈로 기각했으니 참고용 - 판정에 쓰지 않는다.)

**결론: 두 세그먼트의 채택 근거 강도가 다르다.** 소형주 +40%는 ALL·
TRAIN·VALID·TEST 전부 일관되게 개선하는 깨끗한 OOS 프로파일이고, 중형주
+40%+3%트레일링은 ALL 헤드라인은 더 좋지만 VALID를 원 전략보다도
깎는다는 한계가 있다 - 이건 [4]에서 "검증된 봉우리"라고 부른 것을
무효화하지는 않는다(ALL·TRAIN·TEST 개선은 그대로 사실이다), 다만
production 채택 시 이 VALID 약세를 반드시 같이 적어야 한다.

## [7] 트레일링 독립 재현 — 다른 전략에 같은 규칙, 결과는 전략마다 다르다

[6]까지는 전부 pbr_value_v1의 같은 767건을 재슬라이스한 것이라 다중검정
의심을 못 벗는다. 진짜 독립 검증은 **다른 신호로 만든 다른 거래 집합**에
같은 규칙("+40%에서 50%매도 + 잔여 3%트레일링")을 그대로 걸어보는 것이다
- 시가총액 세그먼트 없이 `partial_exit_sweep.py --strategy <id> --triggers
40 --fractions 0.5 --trails 3`으로 전체 포트폴리오 기준 한 번씩 돌렸다
(이미 라이브 페이퍼 슬리브인 `factor_earnings_yield_v1`·`lowmom60_v1`,
그리고 비교 기준으로 `pbr_value_v1` 전체(세그먼트 안 나눈 버전)까지 3개).

| 전략 | 규칙 | ALL | TRAIN | VALID | TEST |
|---|---|---:|---:|---:|---:|
| pbr_value_v1(전체) | 전량 보유 | 0.5210 | 0.566 | 0.151 | 0.663 |
| pbr_value_v1(전체) | +40%/50%+3%트레일 | 0.6912 | 0.633 | 0.139 | 1.281 |
| factor_earnings_yield_v1 | 전량 보유 | 0.4923 | 0.612 | **-0.236** | 0.645 |
| factor_earnings_yield_v1 | +40%/50%+3%트레일 | 0.4987 | 0.664 | **-0.258** | 0.651 |
| lowmom60_v1 | 전량 보유 | 0.4165 | 0.552 | 0.700 | -0.044 |
| lowmom60_v1 | +40%/50%+3%트레일 | 0.6412 | 0.836 | **0.817** | 0.056 |

**결과가 전략마다 갈린다 - "트레일링은 항상 VALID를 깎는다"는 일반 법칙이
아니다.** factor_earnings_yield_v1은 VALID가 더 나빠지고(원래도 음수인데
더 내려감, -0.236→-0.258), lowmom60_v1은 VALID가 오히려 **개선된다**
(0.700→0.817, TRAIN·TEST도 전부 개선 - 부호반전 없이 깨끗하다). PBR은
가운데다.

**더 중요한 발견: pbr_value_v1을 세그먼트 안 나누고 전체로 돌리면 VALID
악화가 훨씬 작다**(0.151→0.139, -0.012)**. [6]의 중형주만 뗀 버전은
같은 규칙에서 VALID가 0.2033→0.0906(-0.1127)로 거의 10배 더 크게
깎였다.** 즉 VALID 약세는 "이 규칙 자체의 성질"이라기보다 **시가총액으로
쪼개서 표본을 얇게 만들자 중형주-VALID라는 좁은 칸(19개월, 거기 걸리는
거래 수는 그보다 더 적다)에서 증폭된 것**에 가깝다 - [6]의 우려(다중검정)를
줄이기는커녕 세그먼트 자체가 잡음을 키우는 방향이라는 방증이 하나 더
늘었다.

**결론: 트레일링을 일반 규칙으로 밀 근거는 없다(전략마다 다름 확인),
그리고 중형주 세그먼트의 VALID 붕괴는 규칙의 본질적 결함이라기보다
세그먼트 분해 자체가 만든 잡음일 가능성이 [6] 때보다 커졌다.** 어느 쪽도
프로덕션 채택을 지지하지 않는다 - "규칙이 나쁘다"와 "세그먼트가 데이터를
너무 잘게 썰었다" 둘 다 HOLD를 유지할 이유이지 KEEP으로 갈 이유는 아니다.
산출: 로컬 실행 결과만(위 표가 숫자 원본) - `reports/2026-09-04-partial-exit/
pbr_value_v1_trail.json`은 그 디렉터리가 원래 09-04 finding의 20%/70%
트리거+트레일링 조합을 담고 있어(gitignore 예외 없이 이미 커밋된 파일)
그 위에 40%/50%+3% 결과를 덮어쓸 뻔했다가 git checkout으로 원복했다 -
같은 파일명을 다른 파라미터로 재사용할 때는 먼저 기존 내용을 확인한다
(이번엔 안 그래서 하마터면 09-04 finding의 원본 인용을 지울 뻔함).
factor_earnings_yield_v1·lowmom60_v1 산출은 이 디렉터리가 gitignore
예외 목록에 없어 로컬에만 있고 커밋 안 됨.

## 판정: HOLD (production 미채택, 근거는 강화됨)

- **채택 후보로 좁혀진 규칙**: 대형주 제외. 중형주는 +40%에서 50% 매도 +
  잔여분 고점대비 -3% 트레일링(ALL Sharpe 0.45→0.64~0.69, 검증된 봉우리) —
  단 [6]에서 확인했듯 **VALID는 오히려 기준선보다 나쁘다**(0.20→0.09,
  부호반전은 없음). 소형주는 +40%에서 50% 매도까지만 신뢰(ALL 0.45→0.55) —
  잔여분 트레일링은 [5]에서 노이즈로 확정, 미채택. [6]에서 확인한 대로
  소형주 +40%는 TRAIN·VALID·TEST 전부 일관 개선해 **중형주보다 OOS 근거가
  깨끗하다.**
- 업종별 세분화는 표본 부족으로 기각 — 추가 세분화가 오히려 신뢰도를
  낮춘다는 걸 확인했다(교훈: 세그먼트를 잘게 쪼갤수록 다중검정 위험이
  커진다, 2026-09-02와 같은 방향).
- [7]에서 트레일링을 factor_earnings_yield_v1·lowmom60_v1에 독립 재현한
  결과 전략마다 갈렸다(EY는 VALID 더 악화, lowmom60은 개선) — "트레일링은
  나쁘다"는 일반화도 근거가 없다. 게다가 pbr_value_v1을 세그먼트 안 나누고
  전체로 재면 중형주만 뗀 버전보다 VALID 악화가 10분의 1 수준이라, [6]의
  VALID 붕괴가 규칙의 결함이 아니라 세그먼트 분해가 만든 잡음일 가능성이
  커졌다.
- production 채택은 여전히 별도 승인 대상(🔴) — 여기서는 세그먼트·트레일링·
  구간별·전략간 재현 축을 검증했을 뿐이다.

## 한계

- 소형주 트레일링은 [5]에서 1%p 단위로 재스윕해 이봉(bimodal) 노이즈임을
  확정했다 — 더 이상 재론하지 않는다.
- 업종 축은 pbr_value_v1 하나로만 봤다 - 다른 전략(성장·모멘텀 계열)에서는
  업종 분포가 다를 수 있다.
- 시가총액·변동성 임계값은 라운드 넘버([ASSUMPTION])다. 자료에 맞춰
  튜닝하지 않았다 - 튜닝하면 이 실험 자체가 다중검정이 된다.
- [6]에서 TRAIN/VALID/TEST 분해를 마쳤다 — `partial-exit-scale-out-
  2026-09.md`가 이미 "VALID 구간에서는 기준선보다 나쁘다"고 지적했는데,
  중형주 세그먼트·트레일링 버전이 정확히 같은 한계를 물려받았음을
  확인했다(소형주는 안 물려받음). production 검토 전 이 비대칭을 반드시
  같이 적어야 한다.
- [6]의 baseline·+40%·+40%+트레일링 비교는 데이터 스냅샷이 [1]·[4]([5]
  포함)와 또 다르다(N=335/276 vs 344/275/276) - A5/A1a가 매일 갱신되므로
  나올 때마다 N이 미세하게 흔들린다. 방향성(중형 VALID 약화·소형 VALID
  강화)은 반복 확인됐지만 소수점 둘째 자리 수치는 실행 시점마다 다시
  잴 수 있다.

스크립트: `partial_exit_segment_sweep.py`(selftest 포함, `--trail-sweep` 모드 추가)
산출: `reports/2026-09-17-partial-exit-segment/pbr_value_v1_{size,sector,vol,trail}.json`
