---
date: 2026-09-04
verdict: REJECT
strategy: production scoring (KR-2.3)
conditions: [score-drop exit, entry >=80, exit 60~75, cause decomposition by valuation axis]
reason: >-
  "고점수에 사고 점수가 떨어지면 판다"는 근거가 없고, 유의한 증거는 전부 반대
  방향이다. 원인을 valuation 축으로 갈라도 마찬가지 - 주가가 올라 비싸져서
  점수가 떨어진 그룹의 이후 20일 수익률이 유지 그룹보다 **높다**(TRAIN 3.76%
  vs 0.80%, t=-3.72). 점수는 횡단면 선택에 쓰는 것이지 보유 종목의 매도
  트리거로 쓰는 것이 아니다.
---

# 점수 기반 청산 Step 0 — 근거 없음, 유의한 증거는 반대 방향

사용자 제안: "우리가 81점에 추천했는데 주가가 오르면 점수가 떨어질 것이다.
그 점수가 70 아래로 내려가면 파는 기준이 있어야 하지 않나."

논리는 이 시스템에서 자기 정합적이다 - 주가가 오르면 valuation 축이 나빠져
점수가 자동으로 내려가므로, 목표주가를 지어내지 않고도 매도 기준이 생긴다.
전략을 만들기 전에 패널에서 먼저 쟀다(2026-09-03 섹터 Step 0 과 같은 순서).

**데이터: 새 수집 0.** `data/backfill/scores/` A5 10년 주간 스냅샷 -
1,201,741행 · 3,001종목 · 2016-01-08~2026-07-31. fwdStatus=OK 인 행만.
구간 TRAIN 2016-01~2022-05 / VALID 2022-05~2023-12 / TEST 2023-12~2026-07.

## [1] 점수 수준과 이후 20일 수익률

| 구간 | TRAIN | VALID | TEST |
|---|---|---|---|
| 0~40 | 0.94% | -0.71% | -0.42% |
| 40~50 | 1.15% | -0.27% | 0.22% |
| 50~60 | 1.23% | 0.06% | 0.64% |
| 60~70 | **1.31%** | 0.18% | 0.82% |
| 70~75 | 1.24% | 0.23% | 1.36% |
| 75~80 | 1.10% | 0.25% | 1.43% |
| 80~85 | 0.83% | **0.85%** | **1.57%** |
| 85~101 | **3.61%** | -0.79% | 0.87% |

VALID·TEST 는 대체로 단조 증가지만 **TRAIN 은 60~70 이 최고고 70~85 가 오히려
낮다.** 최상단(85+)은 3.61% / -0.79% / 0.87% 로 구간마다 제각각이다 - "점수가
높을수록 좋다"가 전 구간에서 성립하지는 않는다.

## [2] 코호트 하락 테스트 — 가설과 반대

80점 이상에서 진입한 뒤 매주 추적. 임계 아래로 떨어진 주의 이후 20일 수익률을
유지된 주와 비교한다(떨어진 뒤에는 코호트에서 뺀다 - 실제 규칙이 거기서 판다).

| 청산임계 | 구간 | 유지 | 하락 | 차이 | t |
|---|---|---|---|---|---|
| 60 | TRAIN | 0.73% | **2.83%** | -2.09% | **-3.91** |
| 60 | VALID | 0.38% | **3.67%** | -3.28% | -1.54 |
| 60 | TEST | 1.15% | 0.87% | +0.28% | 0.26 |
| 65 | TRAIN | 0.80% | 2.17% | -1.38% | **-2.63** |
| 70 | TRAIN | 0.67% | 0.92% | -0.25% | -0.70 |
| 75 | TRAIN | 0.86% | 0.77% | +0.09% | 0.28 |

**점수가 떨어진 시점의 이후 수익률이 오히려 높다.** 유의한 셀은 전부 반대 방향
(TRAIN t=-3.91·-2.63)이고, 임계를 올리면 효과가 사라진다.

## [3] 원인 분해 — 섞여서가 아니었다

[2]가 두 원인을 섞고 있다고 보고 `c.valuation` 축 변화로 갈랐다. valuation 점수가
**내려갔으면 비싸진 것**(주가 상승, 사용자 가설이 팔라는 대상), **올라갔으면
싸진 것**(주가 하락, 역모멘텀 쪽). 결측은 지어내지 않고 unknown 으로 뺐다.

| 임계 | 구간 | 유지 | ★비싸져서 하락 | 싸져서 하락 | t(유지-비싸짐) |
|---|---|---|---|---|---|
| 65 | TRAIN | 0.80% (22,517) | **3.76%** (326) | 1.91% (113) | **-3.72** |
| 65 | VALID | 0.30% (7,547) | **3.64%** (77) | 0.55% (48) | **-2.09** |
| 65 | TEST | 1.39% (8,159) | -0.26% (137) | 0.43% (65) | 1.24 |
| 70 | TRAIN | 0.67% (14,942) | 2.76% (328) | 0.62% (433) | **-2.65** |
| 70 | VALID | 0.36% (4,975) | 2.24% (76) | -0.07% (199) | -1.00 |
| 70 | TEST | 1.70% (5,068) | 0.34% (128) | 0.14% (227) | 1.07 |
| 75 | TRAIN | 0.86% (8,196) | 2.87% (392) | 0.62% (1,046) | **-2.85** |
| 75 | TEST | 1.57% (2,232) | 2.06% (134) | 1.83% (522) | -0.33 |

**분해가 가설을 구하지 못했다 - 오히려 더 확실히 부정한다.** 팔아야 한다고 지목된
그룹("비싸져서 하락")이 **모든 임계의 TRAIN·VALID 에서 가장 높은 이후 수익률을
낸다**(TRAIN 2.76~3.76%, 유지 그룹의 3~5배). 유의성도 그쪽에 있다.

경제적으로 읽으면 - 밸류에이션 점수를 임계 아래로 밀어낼 만큼 오른 종목은
**모멘텀이 붙은 종목**이고, 20일 지평에서는 그게 이어진다. 점수 하락을 매도
신호로 쓰면 **이긴 포지션을 일찍 파는** 전형적 실수가 된다.

TEST 에서만 방향이 뒤집히지만(비싸져서 하락 -0.26% vs 유지 1.39%) t=1.24 로
유의하지 않다. 즉 **반대 효과조차 안정적이지 않다.**

## 같은 날 부분 익절 결과와의 정합성

모순이 아니다. `partial-exit-scale-out-2026-09.md` 에서 +20% 부분 익절은
**CAGR 을 5.49%->5.18% 로 낮추면서** MDD 를 개선했다 - 이긴 포지션을 파는 것이
수익에는 손해라는 방향이 여기와 같다. 부분 익절이 채택 후보인 이유는 수익이
늘어서가 아니라 **위험 대비 가격이 쌌기** 때문이다. 점수 하락 청산은 그 위험
축소마저 제공하지 않는다.

## 판정

**REJECT.** 점수는 **횡단면 선택**(어느 종목을 살까)에 쓰는 것이지 보유 종목의
**매도 트리거**로 쓰는 것이 아니다. 대시보드가 매일 점수를 내면서 매도 기준이
없는 현재 상태는 빠뜨린 게 아니라 **아직 근거를 못 찾은 것**으로 기록한다.

## 한계

- 주간 스냅샷이라 주 1회 판정이다. 초단기에는 애초에 못 쓴다.
- **유동성 필터 없음.** A5 패널은 3,801종목 전체다 - 같은 날 lowmom60 에서
  유니버스가 다르면 결론이 뒤집히는 것을 확인했다. 다만 이 결과는 "신호 없음"
  방향이라 유동성 상위에서 재도 채택으로 바뀔 가능성은 낮다.
- "비싸져서 하락" 표본이 작다(76~392). 반대 방향 효과를 강하게 주장하지 않는다 -
  주장하는 것은 **"팔아야 한다는 근거가 없다"**까지다.
- 진입 규칙("80점에 산다")의 타당성은 별개 질문이고 여기서 다루지 않았다.
- 지평은 d20 하나만 봤다.

스크립트: `score_exit_precheck.py`(selftest 10건)
산출: `reports/2026-09-04-score-exit/precheck_d20.json`
